/**
 * Defines identifiers for all notifications in the system.
 */
export enum NotificationIdentifier {
  USER_NOT_ACTIVATED = 'USER_NOT_ACTIVATED',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS',
  RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS',
  COOKIES_ALLOWED = 'COOKIES_ALLOWED',
  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
  AUTO_LOGOUT_SUCCESS = 'AUTO_LOGOUT_SUCCESS',
  UNKNOWN_AUTHENTICATION_ERROR = 'UNKNOWN_AUTHENTICATION_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  LOG_OUT_TO_USE_THIS_FUNCTION = 'LOG_OUT_TO_USE_THIS_FUNCTION',
  CRAG_CREATED = 'CRAG_CREATED',
  CRAG_UPDATED = 'CRAG_UPDATED',
  CRAG_DELETED = 'CRAG_DELETED',
  SECTOR_CREATED = 'SECTOR_CREATED',
  SECTOR_UPDATED = 'SECTOR_UPDATED',
  SECTOR_DELETED = 'SECTOR_DELETED',
}
