export enum RockExplorerPotential {
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  NONE = 'NONE',
  UNEXPLORED_HIGH = 'UNEXPLORED_HIGH',
  UNEXPLORED_MEDIUM = 'UNEXPLORED_MEDIUM',
  UNEXPLORED_LOW = 'UNEXPLORED_LOW',
}
