services:
  database:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    environment:
      POSTGRES_USER: localcrag
      POSTGRES_DB: localcrag

  storage:
    image: quay.io/minio/minio
    environment:
      MINIO_ROOT_USER: localcrag
      MINIO_INIT_BUCKET: localcrag
    volumes:
      - storage:/data
    ports:
      - "9000:9000"  # Stored Files
      - "9001:9001"  # Web UI
    command: [ "server", "/data", "--console-address", ":9001" ]
    entrypoint: |  # Adopted from https://stackoverflow.com/a/78580294
      /bin/sh -c '
        isAlive() { curl -sf http://127.0.0.1:9000/minio/health/live; }
        minio $$0 "$$@" --quiet & echo $$! > /tmp/minio.pid
        while ! isAlive; do sleep 0.1; done
        mc alias set minio http://127.0.0.1:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD
        mc mb minio/$$MINIO_INIT_BUCKET || true
        mc anonymous set public minio/$$MINIO_INIT_BUCKET
        kill -s INT $$(cat /tmp/minio.pid) && rm /tmp/minio.pid
        while isAlive; do sleep 0.1; done
        exec minio $$0 "$$@"
      '


  server:
    image: ghcr.io/localcrag/localcrag-server:latest
    depends_on:
      - database
      - storage
    container_name: server
    ports:
      - "5000:5000"
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://localcrag:password@database/localcrag"
      SPACES_ACCESS_KEY: localcrag
      SPACES_ENDPOINT: http://storage:9000
      SPACES_BUCKET: localcrag
      SPACES_ACCESS_ENDPOINT: http://localhost:9000
      SPACES_ADDRESSING: path
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3


  client:
    image: ghcr.io/localcrag/localcrag-client:latest
    depends_on:
      - server
    container_name: client
    ports:
      - "4200:4200"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_SCHEDULE: 0 4 * * *
    command: server client
    restart: always

volumes:
  database:
  storage:
