#!/usr/bin/env python3
"""
Append one release note to data/release_notes_manifest.json and add the
translation string to a chosen client locale file (e.g. en.json, de.json).

You enter only the short note key (one JSON object key segment). The manifest
stores ``key`` and ``type`` only; translations live at
``releaseNotes.notes.<key>`` (body) and ``releaseNotes.notes.<key>_title``
(short title for cards) in locale JSON. Also refreshes
``client/src/app/utility/release-note-transloco-keys.ts`` with ``marker()``
calls so transloco-keys-manager extract keeps those keys.

The script refuses a note key that is already listed in the manifest (before
asking for title/body text).

Run from anywhere; paths are resolved from this file's location.

  cd server/src && python3 util/scripts/add_release_note_item.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[4]
_SERVER_SRC = _REPO_ROOT / "server" / "src"
if str(_SERVER_SRC) not in sys.path:
    sys.path.insert(0, str(_SERVER_SRC))

# Client locale JSON and `release-note-transloco-keys.ts` use this prefix.
RELEASE_NOTE_ITEM_I18N_PREFIX = "releaseNotes.notes."


def release_note_item_translation_key(item_key: str) -> str:
    return f"{RELEASE_NOTE_ITEM_I18N_PREFIX}{item_key}"


def release_note_item_title_translation_key(item_key: str) -> str:
    return f"{RELEASE_NOTE_ITEM_I18N_PREFIX}{item_key}_title"


NOTE_TYPES = ("FEATURE", "FIX")


def _repo_root() -> Path:
    return _REPO_ROOT


def _manifest_path(root: Path) -> Path:
    return root / "server" / "src" / "data" / "release_notes_manifest.json"


def _i18n_dir(root: Path) -> Path:
    return root / "client" / "src" / "assets" / "i18n"


def _release_note_transloco_keys_ts_path(root: Path) -> Path:
    return root / "client" / "src" / "app" / "utility" / "release-note-transloco-keys.ts"


def _manifest_item_keys_sorted(manifest_path: Path) -> list[str]:
    data = _load_json(manifest_path)
    if not isinstance(data, dict):
        return []
    items = data.get("items")
    if not isinstance(items, list):
        return []
    keys: set[str] = set()
    for row in items:
        if isinstance(row, dict) and row.get("key"):
            keys.add(str(row["key"]))
    return sorted(keys)


def _write_release_note_transloco_keys(root: Path) -> None:
    """Emit `marker()` entries so transloco-keys-manager keeps dynamic release note keys."""
    manifest_path = _manifest_path(root)
    out_path = _release_note_transloco_keys_ts_path(root)
    keys = _manifest_item_keys_sorted(manifest_path)
    lines = [
        "/**",
        " * Markers for transloco-keys-manager extract to keep release note item keys in sync.",
        " * Regenerated by `server/src/util/scripts/add_release_note_item.py` from",
        " * `server/src/data/release_notes_manifest.json`. Do not edit the marker list by hand.",
        " */",
    ]
    if keys:
        lines.append("import { marker } from '@jsverse/transloco-keys-manager/marker';")
        lines.append("")
    lines.append("export const RELEASE_NOTE_TRANSLOCO_KEYS_FOR_EXTRACT = [")
    for k in keys:
        lines.append(f"  marker('releaseNotes.notes.{k}'),")
        lines.append(f"  marker('releaseNotes.notes.{k}_title'),")
    lines.append("] as const;")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def _top_level_locale_files(i18n_dir: Path) -> list[str]:
    """Locale JSON files directly under i18n/ (not line/, maps/, …)."""
    if not i18n_dir.is_dir():
        return []
    return sorted(p.name for p in i18n_dir.iterdir() if p.suffix == ".json" and p.is_file())


def _prompt_nonempty(label: str) -> str:
    while True:
        value = input(f"{label}: ").strip()
        if value:
            return value
        print("  (required — try again)")


def _prompt_choice(label: str, options: tuple[str, ...], default: str | None = None) -> str:
    opts = "/".join(options)
    hint = f" [{default}]" if default else ""
    while True:
        raw = input(f"{label} ({opts}){hint}: ").strip().upper()
        if not raw and default:
            return default
        if raw in options:
            return raw
        print(f"  Choose one of: {', '.join(options)}")


def _prompt_language(code_to_file: dict[str, Path]) -> Path:
    print("\nAvailable language files (code -> file):")
    for code in sorted(code_to_file):
        print(f"  {code}")
    while True:
        code = input("\nLanguage code (e.g. en, de, en-gym): ").strip()
        if code in code_to_file:
            return code_to_file[code]
        print(f"  Unknown code. Pick from: {', '.join(sorted(code_to_file))}")


def _validate_note_key_suffix(name: str) -> tuple[bool, str]:
    """
    One segment for JSON / Transloco: no dots, no releaseNotes.notes. prefix.
    Identifier-style: letter, then letters, digits, underscores, hyphens.
    """
    if "releaseNotes.notes.".lower() in name.lower():
        return (
            False,
            "Do not include the prefix releaseNotes.notes. — enter only the short key (e.g. betterMaps).",
        )
    if "." in name:
        return False, "The key must be a single segment (no dots)."
    # Valid as a typical JSON string key / identifier (avoids quotes and escaping issues).
    if not re.fullmatch(r"[A-Za-z][A-Za-z0-9_-]*", name):
        return (
            False,
            "Use a letter first, then letters, digits, underscores, or hyphens only (e.g. betterMaps, rn_2026_05).",
        )
    return True, ""


def _load_json(path: Path) -> dict | list:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def _write_json(path: Path, data: dict | list) -> None:
    text = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    path.write_text(text, encoding="utf-8")


def main() -> int:
    root = _repo_root()
    manifest_path = _manifest_path(root)
    i18n_dir = _i18n_dir(root)

    if not manifest_path.is_file():
        print(f"Manifest not found: {manifest_path}", file=sys.stderr)
        return 1

    locale_names = _top_level_locale_files(i18n_dir)
    if not locale_names:
        print(f"No locale JSON files in {i18n_dir}", file=sys.stderr)
        return 1

    code_to_file = {name[: -len(".json")]: i18n_dir / name for name in locale_names}

    print("Add release note item (Ctrl+C to cancel).\n")
    print(
        "Note key — short id only (same as manifest ``key``). "
        "Translations: releaseNotes.notes.<key> (body) and "
        "releaseNotes.notes.<key>_title (short title).\n"
        "Do not type that prefix — e.g. enter betterMaps only.\n"
    )
    item_key = _prompt_nonempty("Note key")
    ok, err = _validate_note_key_suffix(item_key)
    if not ok:
        print(f"Invalid note key: {err}", file=sys.stderr)
        return 1

    translation_key = release_note_item_translation_key(item_key)
    title_translation_key = release_note_item_title_translation_key(item_key)

    manifest = _load_json(manifest_path)
    if not isinstance(manifest, dict) or "items" not in manifest:
        print("Manifest must be a JSON object with an 'items' array.", file=sys.stderr)
        return 1
    items = manifest["items"]
    if not isinstance(items, list):
        print("Manifest 'items' must be an array.", file=sys.stderr)
        return 1

    manifest_keys = {str(row["key"]) for row in items if isinstance(row, dict) and row.get("key")}
    if item_key in manifest_keys:
        print(
            f"Note key {item_key!r} is already listed in {manifest_path} — pick another key.",
            file=sys.stderr,
        )
        return 1

    note_type = _prompt_choice("Note type", NOTE_TYPES, default="FEATURE")

    i18n_path = _prompt_language(code_to_file)

    print(f"\nShort title for {title_translation_key!r} in {i18n_path.name} (single line):")
    title_translation = _prompt_nonempty("Title text")

    print(f"\nBody text for {translation_key!r} in {i18n_path.name} (single line):")
    translation = _prompt_nonempty("Translation text")

    if any(isinstance(row, dict) and row.get("key") == item_key for row in items):
        print(
            f"Note key {item_key!r} was added to the manifest while you were typing — aborting.",
            file=sys.stderr,
        )
        return 1

    i18n_data = _load_json(i18n_path)
    if not isinstance(i18n_data, dict):
        print(f"{i18n_path} must be a JSON object.", file=sys.stderr)
        return 1

    existing_keys = [k for k in (translation_key, title_translation_key) if k in i18n_data]
    if existing_keys:
        replace = (
            input(
                f"\nKey(s) already exist in {i18n_path.name}: {', '.join(repr(k) for k in existing_keys)}. "
                "Overwrite all listed? [y/N]: "
            )
            .strip()
            .lower()
        )
        if replace != "y":
            print("Aborted.")
            return 1

    items.append(
        {
            "key": item_key,
            "type": note_type,
        }
    )
    i18n_data[title_translation_key] = title_translation
    i18n_data[translation_key] = translation

    _write_json(manifest_path, manifest)
    _write_json(i18n_path, i18n_data)
    _write_release_note_transloco_keys(root)

    print("\nDone.")
    print(f"  Manifest key:      {item_key}")
    print(f"  Title key:         {title_translation_key}")
    print(f"  Body key:          {translation_key}")
    print(f"  Manifest:          {manifest_path}")
    print(f"  Locale:            {i18n_path}")
    print("\nAdd the same title and body keys to other locale files when you are ready.")
    print(f"  Transloco markers: {_release_note_transloco_keys_ts_path(root)}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("\nCancelled.", file=sys.stderr)
        raise SystemExit(130)
