/**
 * Markers for transloco-keys-manager extract to keep release note item keys in sync.
 * Regenerated by `server/src/util/scripts/add_release_note_item.py` from
 * `server/src/data/release_notes_manifest.json`. Do not edit the marker list by hand.
 */
import { marker } from '@jsverse/transloco-keys-manager/marker';

export const RELEASE_NOTE_TRANSLOCO_KEYS_FOR_EXTRACT = [
  marker('releaseNotes.section.FEATURE'),
  marker('releaseNotes.section.FIX'),
  marker('releaseNotes.notes.notifications'),
  marker('releaseNotes.notes.notifications_title'),
] as const;
