/**
 * Markers for transloco-keys-manager extract to keep release note item keys in sync.
 * Regenerated by `server/src/util/scripts/add_release_note_item.py` from
 * `server/src/data/release_notes_manifest.json`. Do not edit the marker list by hand.
 */

export const RELEASE_NOTE_TRANSLOCO_KEYS_FOR_EXTRACT = [] as const;
