/**
 * Markers for transloco-keys-manager extract to keep release note item keys in sync.
 * Regenerated by `server/src/util/scripts/add_release_note_item.py` from
 * `server/src/data/release_notes_manifest.json`. Do not edit the marker list by hand.
 */
import { marker } from '@jsverse/transloco-keys-manager/marker';

export const RELEASE_NOTE_TRANSLOCO_KEYS_FOR_EXTRACT = [
  marker('releaseNotes.notes.darkMode'),
  marker('releaseNotes.notes.darkMode_title'),
  marker('releaseNotes.notes.frenchLanguage'),
  marker('releaseNotes.notes.frenchLanguage_title'),
  marker('releaseNotes.notes.lineFilters'),
  marker('releaseNotes.notes.lineFilters_title'),
  marker('releaseNotes.notes.newOrderOptions'),
  marker('releaseNotes.notes.newOrderOptions_title'),
] as const;
