"""empty message

Revision ID: 019f6bdbb573
Revises: d1ead0ff6362
Create Date: 2025-10-18 20:50:20.398737

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "019f6bdbb573"
down_revision = "d1ead0ff6362"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("disable_fa_in_ascents", sa.Boolean(), server_default="false", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance_settings", schema=None) as batch_op:
        batch_op.drop_column("disable_fa_in_ascents")

    # ### end Alembic commands ###
