"""empty message

Revision ID: 041cf4227d18
Revises: d320ced7814f
Create Date: 2025-11-08 17:10:22.431527

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "041cf4227d18"
down_revision = "d320ced7814f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("root_id", sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f("ix_comments_root_id"), ["root_id"], unique=False)
        batch_op.create_unique_constraint(None, ["id"])
        batch_op.create_foreign_key(None, "comments", ["root_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_index(batch_op.f("ix_comments_root_id"))
        batch_op.drop_column("root_id")

    # ### end Alembic commands ###
