"""empty message

Revision ID: 058c3bf674c9
Revises: d1ed8e492759
Create Date: 2024-03-31 18:02:57.041138

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "058c3bf674c9"
down_revision = "d1ed8e492759"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("deleted")
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("locked")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("locked", sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column("deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column("deleted", sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
