"""empty message

Revision ID: 05ebc3b1cffa
Revises: 1a03d846b4d3
Create Date: 2026-03-24 09:23:55.890657

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "05ebc3b1cffa"
down_revision = "1a03d846b4d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todos", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("todos_area_id_fkey"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("todos_sector_id_fkey"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("todos_crag_id_fkey"), type_="foreignkey")
        batch_op.drop_column("area_id")
        batch_op.drop_column("crag_id")
        batch_op.drop_column("sector_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todos", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sector_id", sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column("crag_id", sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column("area_id", sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f("todos_crag_id_fkey"), "crags", ["crag_id"], ["id"])
        batch_op.create_foreign_key(batch_op.f("todos_sector_id_fkey"), "sectors", ["sector_id"], ["id"])
        batch_op.create_foreign_key(batch_op.f("todos_area_id_fkey"), "areas", ["area_id"], ["id"])

    # ### end Alembic commands ###
