"""empty message

Revision ID: 0b20e4ecbe5c
Revises: e1695a5ba794
Create Date: 2024-05-26 18:40:38.047751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b20e4ecbe5c'
down_revision = 'e1695a5ba794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_column('ascent_count')

    with op.batch_alter_table('crags', schema=None) as batch_op:
        batch_op.drop_column('ascent_count')

    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.drop_column('ascent_count')

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_column('ascent_count')

    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.drop_column('ascent_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ascent_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ascent_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))

    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ascent_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))

    with op.batch_alter_table('crags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ascent_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))

    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ascent_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
