"""empty message

Revision ID: 0f6f40500708
Revises: 34419ae27520
Create Date: 2024-04-01 20:43:28.343223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6f40500708'
down_revision = '34419ae27520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_constraint('areas_created_by_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('crags', schema=None) as batch_op:
        batch_op.drop_constraint('crags_created_by_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint('files_created_by_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('line_paths', schema=None) as batch_op:
        batch_op.drop_constraint('line_paths_created_by_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.drop_constraint('lines_created_by_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_constraint('menu_items_created_by_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('menu_pages', schema=None) as batch_op:
        batch_op.drop_constraint('menu_pages_created_by_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_created_by_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_constraint('regions_created_by_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.drop_constraint('sectors_created_by_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('topo_images', schema=None) as batch_op:
        batch_op.drop_constraint('topo_images_created_by_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_created_by_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_created_by_id_fkey', 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('topo_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('topo_images_created_by_id_fkey', 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sectors_created_by_id_fkey', 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('regions_created_by_id_fkey', 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('posts_created_by_id_fkey', 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('menu_pages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('menu_pages_created_by_id_fkey', 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('menu_items_created_by_id_fkey', 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('lines_created_by_id_fkey', 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('line_paths', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('line_paths_created_by_id_fkey', 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('files_created_by_id_fkey', 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('crags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('crags_created_by_id_fkey', 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('areas_created_by_id_fkey', 'users', ['created_by_id'], ['id'])

    # ### end Alembic commands ###
