"""empty message

Revision ID: 128e1bc574bc
Revises: c1b2a9d5e77f
Create Date: 2026-04-25 23:30:02.124224

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "128e1bc574bc"
down_revision = "c1b2a9d5e77f"
branch_labels = None
depends_on = None


def upgrade():
    notificationtypeenum = sa.Enum(
        "comment_reply",
        "reaction",
        "fa_moderation_removed",
        name="notificationtypeenum",
        create_type=False,
    )
    notificationdigestfrequencyenum = sa.Enum(
        "daily",
        "weekly",
        name="notificationdigestfrequencyenum",
        create_type=True,
    )

    # notificationtypeenum will be created automatically by create_table
    notificationdigestfrequencyenum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", notificationtypeenum, nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("time_created", sa.DateTime(), nullable=False),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notifications_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_type"), ["type"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("account_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("reaction_notifications_enabled", sa.Boolean(), server_default="false", nullable=False)
        )
        batch_op.add_column(
            sa.Column("system_notifications_enabled", sa.Boolean(), server_default="true", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "notification_digest_frequency", notificationdigestfrequencyenum, server_default="daily", nullable=False
            )
        )

    with op.batch_alter_table("reactions", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("recent_searches", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recent_searches", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("reactions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("account_settings", schema=None) as batch_op:
        batch_op.drop_column("notification_digest_frequency")
        batch_op.drop_column("system_notifications_enabled")
        batch_op.drop_column("reaction_notifications_enabled")

    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_type"))
        batch_op.drop_index(batch_op.f("ix_notifications_actor_id"))

    op.drop_table("notifications")

    # Drop enums last (after all dependent columns/tables are removed).
    # Use create_type=False here as well; we only want to DROP TYPE.
    notificationdigestfrequencyenum = sa.Enum(
        "daily",
        "weekly",
        name="notificationdigestfrequencyenum",
        create_type=False,
    )
    notificationtypeenum = sa.Enum(
        "comment_reply",
        "reaction",
        "fa_moderation_removed",
        name="notificationtypeenum",
        create_type=False,
    )
    notificationdigestfrequencyenum.drop(op.get_bind(), checkfirst=True)
    notificationtypeenum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
