"""empty message

Revision ID: 1301e651ea69
Revises: edd3566bce56
Create Date: 2024-06-08 09:32:00.393119

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1301e651ea69'
down_revision = 'edd3566bce56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.alter_column('grade_value',
                              existing_type=sa.INTEGER(),
                              nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.alter_column('grade_value',
                              existing_type=sa.INTEGER(),
                              nullable=True)

    # ### end Alembic commands ###
