"""empty message

Revision ID: 14dc45b4214e
Revises: 28f64bea4755
Create Date: 2025-12-05 00:04:20.082057

"""

import uuid

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "14dc45b4214e"
down_revision = "28f64bea4755"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("comment_reply_mails_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_account_settings_user_id"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "comments",
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("object_type", sa.Unicode(length=255), nullable=True),
        sa.Column("object_id", sa.UUID(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("root_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=True),
        sa.Column("time_updated", sa.DateTime(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["comments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["root_id"],
            ["comments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_comments_root_id"), ["root_id"], unique=False)

    # Create missing account settings
    bind = op.get_bind()
    missing_rows = bind.execute(
        sa.text("SELECT u.id FROM users u LEFT JOIN account_settings a ON a.user_id = u.id WHERE a.user_id IS NULL")
    ).fetchall()
    if not missing_rows:
        return

    insert_stmt = sa.text(
        "INSERT INTO account_settings (id, user_id, comment_reply_mails_enabled) VALUES (:id, :user_id, true)"
    )
    for (user_id,) in missing_rows:
        bind.execute(insert_stmt, {"id": str(uuid.uuid4()), "user_id": user_id})

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comments_root_id"))

    op.drop_table("comments")
    op.drop_table("account_settings")
    # ### end Alembic commands ###
