"""empty message

Revision ID: 1a03d846b4d3
Revises: 8b1eb056b52a
Create Date: 2026-03-24 09:06:26.614798

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1a03d846b4d3"
down_revision = "8b1eb056b52a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ascents", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("ascents_sector_id_fkey"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("ascents_area_id_fkey"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("ascents_crag_id_fkey"), type_="foreignkey")
        batch_op.drop_column("area_id")
        batch_op.drop_column("crag_id")
        batch_op.drop_column("sector_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ascents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sector_id", sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column("crag_id", sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column("area_id", sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f("ascents_crag_id_fkey"), "crags", ["crag_id"], ["id"])
        batch_op.create_foreign_key(batch_op.f("ascents_area_id_fkey"), "areas", ["area_id"], ["id"])
        batch_op.create_foreign_key(batch_op.f("ascents_sector_id_fkey"), "sectors", ["sector_id"], ["id"])

    # ### end Alembic commands ###
