"""empty message

Revision ID: 216ad4a52720
Revises: 626e3b6d3994
Create Date: 2024-03-23 18:27:46.601826

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '216ad4a52720'
down_revision = '626e3b6d3994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_items',
                    sa.Column('type',
                              sa.Enum('MENU_PAGE', 'TOPO', 'NEWS', 'YOUTUBE', 'INSTAGRAM', name='menuitemtypeenum'),
                              nullable=False),
                    sa.Column('position', sa.Enum('BOTTOM', 'TOP', name='menuitempositionenum'), nullable=False),
                    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('menu_page_id', sa.UUID(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('time_created', sa.DateTime(), nullable=True),
                    sa.Column('time_updated', sa.DateTime(), nullable=True),
                    sa.Column('created_by_id', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['menu_page_id'], ['menu_pages.id'], ),
                    sa.PrimaryKeyConstraint('menu_page_id', 'id'),
                    sa.UniqueConstraint('id')
                    )
    with op.batch_alter_table('menu_pages', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_pages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('menu_items')
    # ### end Alembic commands ###
