"""empty message

Revision ID: 21e241cef1c2
Revises: 006f19c29739
Create Date: 2024-04-21 11:34:46.190199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21e241cef1c2'
down_revision = '006f19c29739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rankings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('top_values', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=True))
        batch_op.add_column(sa.Column('top_fa_values', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rankings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('top_fa_values')
        batch_op.drop_column('top_values')

    # ### end Alembic commands ###
