"""empty message

Revision ID: 222587e858f7
Revises: 6c91185b5879
Create Date: 2024-01-27 00:00:09.871463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222587e858f7'
down_revision = '6c91185b5879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.alter_column('video',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.alter_column('video',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
