"""empty message

Revision ID: 244e1996b205
Revises: 4c31851e4fd2
Create Date: 2024-04-21 23:25:50.410526

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '244e1996b205'
down_revision = '4c31851e4fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rankings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_fa_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rankings', schema=None) as batch_op:
        batch_op.drop_column('total_fa_count')
        batch_op.drop_column('total_count')

    # ### end Alembic commands ###
