"""empty message

Revision ID: 249fb274004c
Revises: 3a6b15bd42ca
Create Date: 2024-06-29 21:52:08.646456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249fb274004c'
down_revision = '3a6b15bd42ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description2', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_column('description2')

    # ### end Alembic commands ###
