"""empty message

Revision ID: 2c6af51b763d
Revises: ffb5158bf4ab
Create Date: 2022-09-26 09:57:08.489960

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2c6af51b763d"
down_revision = "ffb5158bf4ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("files", "width", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("files", "height", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("files", "height", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("files", "width", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
