"""empty message

Revision ID: 2fb74e915d95
Revises: a26b5671d032
Create Date: 2024-04-16 15:03:20.846023

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2fb74e915d95'
down_revision = 'a26b5671d032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.drop_column('user_rating')

    # ### end Alembic commands ###
