"""empty message

Revision ID: 2fdca42b075f
Revises: 3bda486a1a70
Create Date: 2025-07-21 21:06:04.974083

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2fdca42b075f"
down_revision = "3bda486a1a70"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fa_date", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.drop_column("fa_date")

    # ### end Alembic commands ###
