"""empty message

Revision ID: 30651a1bdf23
Revises: 9b1ebe41f9c8
Create Date: 2024-05-05 19:11:41.762341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30651a1bdf23'
down_revision = '9b1ebe41f9c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('searchables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sa.Boolean(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('searchables', schema=None) as batch_op:
        batch_op.drop_column('secret')

    # ### end Alembic commands ###
