"""empty message

Revision ID: 34419ae27520
Revises: 5940a7356b0f
Create Date: 2024-04-01 15:43:02.920501

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "34419ae27520"
down_revision = "5940a7356b0f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("moderator", sa.Boolean(), server_default="0", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("moderator")

    # ### end Alembic commands ###
