"""empty message

Revision ID: 3619ac5c946b
Revises: 1a57ceb2300e
Create Date: 2024-02-08 22:51:19.288906

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3619ac5c946b"
down_revision = "1a57ceb2300e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.drop_column("video")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.add_column(sa.Column("video", sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
