"""empty message

Revision ID: 388dbc0da585
Revises: 5d2ddfe9e865
Create Date: 2024-02-17 22:46:52.115261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388dbc0da585'
down_revision = '5d2ddfe9e865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
