"""empty message

Revision ID: 3a2319286dd7
Revises: 3a6b15bd42ca
Create Date: 2024-06-30 00:27:53.930705

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3a2319286dd7"
down_revision = "3a6b15bd42ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("superadmin", sa.Boolean(), server_default="0", nullable=False))
    op.execute("UPDATE users SET superadmin = True WHERE admin = True")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("superadmin")

    # ### end Alembic commands ###
