"""empty message

Revision ID: 4021fb139c9b
Revises: 497c95fffabe
Create Date: 2024-04-27 23:35:54.073999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4021fb139c9b'
down_revision = '497c95fffabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searchables',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('CRAG', 'SECTOR', 'AREA', 'LINE', 'USER', name='searchableitemtypeenum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('type', 'id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('searchables')
    # ### end Alembic commands ###
