"""empty message

Revision ID: 41e0b0cadb49
Revises: 0b20e4ecbe5c
Create Date: 2024-05-26 20:07:30.691088

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '41e0b0cadb49'
down_revision = '0b20e4ecbe5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rankings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rankings', schema=None) as batch_op:
        batch_op.drop_column('secret')

    # ### end Alembic commands ###
