"""empty message

Revision ID: 47d85d8042d0
Revises: ab2fd18fb216
Create Date: 2024-02-06 10:09:10.238994

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import orm
from sqlalchemy.ext.declarative import declarative_base

# revision identifiers, used by Alembic.
revision = "47d85d8042d0"
down_revision = "ab2fd18fb216"
branch_labels = None
depends_on = None

Base = declarative_base()


class Crag(Base):
    __tablename__ = "crags"

    id = sa.Column(sa.String, primary_key=True)
    order_index = sa.Column(sa.Integer)


class Sector(Base):
    __tablename__ = "sectors"

    id = sa.Column(sa.String, primary_key=True)
    order_index = sa.Column(sa.Integer)
    crag_id = sa.Column(sa.String)


class Area(Base):
    __tablename__ = "areas"

    id = sa.Column(sa.String, primary_key=True)
    order_index = sa.Column(sa.Integer)
    sector_id = sa.Column(sa.String)


class TopoImage(Base):
    __tablename__ = "topo_images"

    id = sa.Column(sa.String, primary_key=True)
    order_index = sa.Column(sa.Integer)
    area_id = sa.Column(sa.String)


class LinePath(Base):
    __tablename__ = "line_paths"

    id = sa.Column(sa.String, primary_key=True)
    order_index = sa.Column(sa.Integer)
    topo_image_id = sa.Column(sa.String)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("areas", schema=None) as batch_op:
        batch_op.add_column(sa.Column("order_index", sa.Integer(), server_default="0", nullable=False))

    with op.batch_alter_table("crags", schema=None) as batch_op:
        batch_op.add_column(sa.Column("order_index", sa.Integer(), server_default="0", nullable=False))

    with op.batch_alter_table("line_paths", schema=None) as batch_op:
        batch_op.add_column(sa.Column("order_index", sa.Integer(), server_default="0", nullable=False))

    with op.batch_alter_table("sectors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("order_index", sa.Integer(), server_default="0", nullable=False))

    with op.batch_alter_table("topo_images", schema=None) as batch_op:
        batch_op.add_column(sa.Column("order_index", sa.Integer(), server_default="0", nullable=False))

    # Set initial order IDs
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    crags = session.query(Crag).all()
    session.add_all(crags)
    crag_order_index = 0
    for crag in crags:
        crag.order_index = crag_order_index
        crag_order_index += 1

        sectors = session.query(Sector).filter_by(crag_id=crag.id).all()
        session.add_all(sectors)
        sector_order_index = 0
        for sector in sectors:
            sector.order_index = sector_order_index
            sector_order_index += 1

            areas = session.query(Area).filter_by(sector_id=sector.id).all()
            session.add_all(areas)
            area_order_index = 0
            for area in areas:
                area.order_index = area_order_index
                area_order_index += 1

                topo_images = session.query(TopoImage).filter_by(area_id=area.id).all()
                session.add_all(topo_images)
                topo_image_order_index = 0
                for topo_image in topo_images:
                    topo_image.order_index = topo_image_order_index
                    topo_image_order_index += 1

                    line_paths = session.query(LinePath).filter_by(topo_image_id=topo_image.id).all()
                    session.add_all(line_paths)
                    line_path_order_index = 0
                    for line_path in line_paths:
                        line_path.order_index = line_path_order_index
                        line_path_order_index += 1

    session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("topo_images", schema=None) as batch_op:
        batch_op.drop_column("order_index")

    with op.batch_alter_table("sectors", schema=None) as batch_op:
        batch_op.drop_column("order_index")

    with op.batch_alter_table("line_paths", schema=None) as batch_op:
        batch_op.drop_column("order_index")

    with op.batch_alter_table("crags", schema=None) as batch_op:
        batch_op.drop_column("order_index")

    with op.batch_alter_table("areas", schema=None) as batch_op:
        batch_op.drop_column("order_index")

    # ### end Alembic commands ###
