"""empty message

Revision ID: 4c31851e4fd2
Revises: 21e241cef1c2
Create Date: 2024-04-21 23:24:07.850225

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4c31851e4fd2"
down_revision = "21e241cef1c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rankings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("top_10_exponential", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("top_25_exponential", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("total_exponential", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("total_fa_exponential", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rankings", schema=None) as batch_op:
        batch_op.drop_column("total_fa_exponential")
        batch_op.drop_column("total_exponential")
        batch_op.drop_column("top_25_exponential")
        batch_op.drop_column("top_10_exponential")

    # ### end Alembic commands ###
