"""empty message

Revision ID: 538e17ab1cad
Revises: 17271423167a
Create Date: 2024-04-10 08:15:43.867514

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '538e17ab1cad'
down_revision = '17271423167a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String()))
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
