"""Added 'old' property to lines and topo_images

Revision ID: 544c5d2ae547
Revises: 04cd54785ed2
Create Date: 2024-09-29 07:17:11.187044

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "544c5d2ae547"
down_revision = "04cd54785ed2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.add_column(sa.Column("old", sa.Boolean(), server_default="false", nullable=False))

    with op.batch_alter_table("topo_images", schema=None) as batch_op:
        batch_op.add_column(sa.Column("old", sa.Boolean(), server_default="false", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("topo_images", schema=None) as batch_op:
        batch_op.drop_column("old")

    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.drop_column("old")

    # ### end Alembic commands ###
