"""empty message

Revision ID: 55a7e0a820e3
Revises: b49d71589bbb
Create Date: 2025-07-27 14:14:18.545015

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "55a7e0a820e3"
down_revision = "b49d71589bbb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("display_user_ratings", sa.Boolean(), server_default="false", nullable=False))
        batch_op.add_column(sa.Column("display_user_grades", sa.Boolean(), server_default="false", nullable=False))
        # Set new columns to the value of the old column before dropping it
    op.execute("UPDATE instance_settings SET display_user_ratings = display_user_grades_ratings")
    op.execute("UPDATE instance_settings SET display_user_grades = display_user_grades_ratings")
    with op.batch_alter_table("instance_settings", schema=None) as batch_op:
        batch_op.drop_column("display_user_grades_ratings")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "display_user_grades_ratings",
                sa.BOOLEAN(),
                server_default=sa.text("false"),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("display_user_grades")
        batch_op.drop_column("display_user_ratings")

    # ### end Alembic commands ###
