"""empty message

Revision ID: 58e8d64cccf2
Revises: 60c6011f6eb1
Create Date: 2024-01-24 12:35:47.088236

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "58e8d64cccf2"
down_revision = "60c6011f6eb1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.add_column(sa.Column("gradeName", sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column("gradeScale", sa.String(length=120), nullable=False))
        batch_op.drop_column("grade")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.add_column(sa.Column("grade", sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column("gradeScale")
        batch_op.drop_column("gradeName")

    # ### end Alembic commands ###
