"""empty message

Revision ID: 5940a7356b0f
Revises: 058c3bf674c9
Create Date: 2024-04-01 11:59:28.451212

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5940a7356b0f'
down_revision = '058c3bf674c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('new_email_hash', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('new_email_hash_created', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_unique_constraint(None, ['new_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('new_email_hash_created')
        batch_op.drop_column('new_email_hash')
        batch_op.drop_column('new_email')

    # ### end Alembic commands ###
