"""empty message

Revision ID: 61162ef36089
Revises: 497c95fffabe
Create Date: 2024-04-25 12:17:13.095090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61162ef36089'
down_revision = '497c95fffabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searchables',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('CRAG', 'SECTOR', 'AREA', 'LINE', 'USER', name='searchableitemtypeenum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('type', 'id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('searchables')
    # ### end Alembic commands ###
