"""empty message

Revision ID: 6c048cf0136a
Revises: b51c42aabe03
Create Date: 2024-11-09 21:40:58.594278

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "6c048cf0136a"
down_revision = "b51c42aabe03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    op.execute("ALTER TYPE menuitemtypeenum ADD VALUE 'GALLERY'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
