"""Add color to lines

Revision ID: 6fe7f8cbfc44
Revises: fc965fe6216c
Create Date: 2024-10-27 15:04:21.395990

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6fe7f8cbfc44"
down_revision = "fc965fe6216c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.add_column(sa.Column("color", sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.drop_column("color")

    # ### end Alembic commands ###
