"""empty message

Revision ID: 732e0c9ffae2
Revises: b094ecca2b5a
Create Date: 2025-11-14 21:22:31.235376

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "732e0c9ffae2"
down_revision = "b094ecca2b5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.alter_column("message", existing_type=sa.TEXT(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.alter_column("message", existing_type=sa.TEXT(), nullable=False)

    # ### end Alembic commands ###
