"""empty message

Revision ID: 84cb554d4c2b
Revises: bad26c00d5c5
Create Date: 2024-03-26 15:50:45.162660

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "84cb554d4c2b"
down_revision = "bad26c00d5c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("arrow_color", sa.String(length=7), server_default="#FFE016", nullable=False))
        batch_op.add_column(
            sa.Column("arrow_text_color", sa.String(length=7), server_default="#000000", nullable=False)
        )
        batch_op.add_column(
            sa.Column("arrow_highlight_color", sa.String(length=7), server_default="#FF0000", nullable=False)
        )
        batch_op.add_column(
            sa.Column("arrow_highlight_text_color", sa.String(length=7), server_default="#FFFFFF", nullable=False)
        )
        batch_op.create_unique_constraint(None, ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance_settings", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("arrow_highlight_text_color")
        batch_op.drop_column("arrow_highlight_color")
        batch_op.drop_column("arrow_text_color")
        batch_op.drop_column("arrow_color")

    # ### end Alembic commands ###
