"""empty message

Revision ID: 871510303302
Revises: 6c048cf0136a
Create Date: 2024-11-16 18:26:33.276941

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "871510303302"
down_revision = "6c048cf0136a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.add_column(sa.Column("secret", sa.Boolean(), server_default="0", nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_column("secret")

    # ### end Alembic commands ###
