"""empty message

Revision ID: 885c530b570c
Revises: 216ad4a52720
Create Date: 2024-03-24 20:22:22.094499

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '885c530b570c'
down_revision = '216ad4a52720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE menu_items DROP CONSTRAINT menu_items_pkey CASCADE')

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.alter_column('menu_page_id',
                              existing_type=sa.UUID(),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.alter_column('menu_page_id',
                              existing_type=sa.UUID(),
                              nullable=False)

    # ### end Alembic commands ###
