"""empty message

Revision ID: 8b1eb056b52a
Revises: 14dc45b4214e
Create Date: 2026-03-06 20:48:50.590854

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8b1eb056b52a"
down_revision = "7d381d88dc85"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account_settings", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("areas", schema=None) as batch_op:
        batch_op.add_column(sa.Column("blocweather_url", sa.String(length=255), nullable=True))

    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("crags", schema=None) as batch_op:
        batch_op.add_column(sa.Column("blocweather_url", sa.String(length=255), nullable=True))

    with op.batch_alter_table("sectors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("blocweather_url", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sectors", schema=None) as batch_op:
        batch_op.drop_column("blocweather_url")

    with op.batch_alter_table("crags", schema=None) as batch_op:
        batch_op.drop_column("blocweather_url")

    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("areas", schema=None) as batch_op:
        batch_op.drop_column("blocweather_url")

    with op.batch_alter_table("account_settings", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
