"""empty message

Revision ID: 90792bd238d6
Revises: 721ec50bca21
Create Date: 2023-05-07 17:32:02.605625

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90792bd238d6"
down_revision = "721ec50bca21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crags", schema=None) as batch_op:
        batch_op.add_column(sa.Column("short_description", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crags", schema=None) as batch_op:
        batch_op.drop_column("short_description")

    # ### end Alembic commands ###
