"""empty message

Revision ID: 93468e6cf962
Revises: 5f70751349da
Create Date: 2023-07-24 16:26:59.714939

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '93468e6cf962'
down_revision = '5f70751349da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.alter_column('slug',
                              existing_type=sa.VARCHAR(),
                              nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.alter_column('slug',
                              existing_type=sa.VARCHAR(),
                              nullable=True)

    # ### end Alembic commands ###
