"""empty message

Revision ID: a06da5a22433
Revises: b7032dd74cfd
Create Date: 2024-02-10 13:05:10.912389

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a06da5a22433"
down_revision = "b7032dd74cfd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sectors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("lat", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("lng", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sectors", schema=None) as batch_op:
        batch_op.drop_column("lng")
        batch_op.drop_column("lat")

    # ### end Alembic commands ###
