"""empty message

Revision ID: ab2fd18fb216
Revises: ce9a76707ac4
Create Date: 2024-02-06 08:52:14.452072

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ab2fd18fb216"
down_revision = "ce9a76707ac4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.alter_column(
            "starting_position",
            existing_type=postgresql.ENUM("SIT", "STAND", "CROUCH", "FRENCH", "CANDLE", name="startingpositionenum"),
            nullable=False,
        )
        batch_op.drop_column("sitstart")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sitstart", sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.alter_column(
            "starting_position",
            existing_type=postgresql.ENUM("SIT", "STAND", "CROUCH", "FRENCH", "CANDLE", name="startingpositionenum"),
            nullable=True,
        )

    # ### end Alembic commands ###
