"""empty message

Revision ID: ab57a16e66a9
Revises: 5c1050b727b9
Create Date: 2024-02-05 20:16:59.074240

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab57a16e66a9"
down_revision = "5c1050b727b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.alter_column("rating", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.alter_column("rating", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
