"""empty message

Revision ID: b094ecca2b5a
Revises: 041cf4227d18
Create Date: 2025-11-14 21:17:30.217518

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b094ecca2b5a"
down_revision = "041cf4227d18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default="false"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_column("is_deleted")

    # ### end Alembic commands ###
