"""empty message

Revision ID: b49d71589bbb
Revises: 2fdca42b075f
Create Date: 2025-07-21 22:06:16.637989

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b49d71589bbb"
down_revision = "2fdca42b075f"
branch_labels = None
depends_on = None


def upgrade():
    fadefaultformatenum = sa.Enum("DATE", "YEAR", name="fadefaultformatenum")
    fadefaultformatenum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table("instance_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fa_default_format", fadefaultformatenum, server_default="YEAR", nullable=False))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance_settings", schema=None) as batch_op:
        batch_op.drop_column("fa_default_format")

    # ### end Alembic commands ###
