"""empty message

Revision ID: b51c42aabe03
Revises: 04cd54785ed2
Create Date: 2024-10-26 13:39:44.634855

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b51c42aabe03"
down_revision = "04cd54785ed2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("object_type", sa.Unicode(length=255), nullable=True),
        sa.Column("object_id", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "gallery_images",
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=True),
        sa.Column("time_updated", sa.DateTime(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.PrimaryKeyConstraint("file_id", "id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "gallery_image_tags",
        sa.Column("tag_id", sa.UUID(), nullable=True),
        sa.Column("gallery_image_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gallery_image_id"],
            ["gallery_images.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gallery_image_tags")
    op.drop_table("gallery_images")
    op.drop_table("tags")
    # ### end Alembic commands ###
