"""empty message

Revision ID: ba171c2ccd15
Revises: e3d4287d48d8
Create Date: 2024-04-05 20:44:32.508454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba171c2ccd15'
down_revision = 'e3d4287d48d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ascents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('with_kneepad', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ascents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('with_kneepad')

    # ### end Alembic commands ###
