"""empty message

Revision ID: bad26c00d5c5
Revises: 885c530b570c
Create Date: 2024-03-26 11:19:57.613344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad26c00d5c5'
down_revision = '885c530b570c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=True),
    sa.Column('instance_name', sa.String(length=120), nullable=False),
    sa.Column('copyright_owner', sa.String(length=120), nullable=False),
    sa.Column('youtube_url', sa.String(length=120), nullable=True),
    sa.Column('instagram_url', sa.String(length=120), nullable=True),
    sa.Column('logo_image_id', sa.UUID(), nullable=True),
    sa.Column('favicon_image_id', sa.UUID(), nullable=True),
    sa.Column('auth_bg_image_id', sa.UUID(), nullable=True),
    sa.Column('main_bg_image_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['auth_bg_image_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['favicon_image_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['logo_image_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['main_bg_image_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instance_settings')
    # ### end Alembic commands ###
