"""empty message

Revision ID: c2beb594f233
Revises: f6d0d0d98cbf
Create Date: 2025-01-15 17:33:06.551306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2beb594f233'
down_revision = 'f6d0d0d98cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('closed_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('crags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('closed_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('closed_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('closed_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.drop_column('closed_reason')
        batch_op.drop_column('closed')

    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.drop_column('closed_reason')
        batch_op.drop_column('closed')

    with op.batch_alter_table('crags', schema=None) as batch_op:
        batch_op.drop_column('closed_reason')
        batch_op.drop_column('closed')

    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_column('closed_reason')
        batch_op.drop_column('closed')

    # ### end Alembic commands ###
