"""empty message

Revision ID: ccc1744ecb5f
Revises: 41e0b0cadb49
Create Date: 2024-06-01 15:57:57.142387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccc1744ecb5f'
down_revision = '41e0b0cadb49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rankings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('top_50', sa.Integer(), nullable=True))
        batch_op.drop_column('top_10_fa_exponential')
        batch_op.drop_column('total_exponential')
        batch_op.drop_column('top_10_exponential')
        batch_op.drop_column('total_fa_exponential')
        batch_op.drop_column('top_25')
        batch_op.drop_column('total_fa')
        batch_op.drop_column('total_fa_count')
        batch_op.drop_column('top_25_exponential')
        batch_op.drop_column('total')
        batch_op.drop_column('top_10_fa')
        batch_op.drop_column('top_fa_values')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rankings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('top_fa_values', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('top_10_fa', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('top_25_exponential', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_fa_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_fa', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('top_25', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_fa_exponential', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('top_10_exponential', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_exponential', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('top_10_fa_exponential', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('top_50')

    # ### end Alembic commands ###
