"""empty message

Revision ID: cda23343448f
Revises: 47d85d8042d0
Create Date: 2024-02-08 22:16:10.680585

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cda23343448f"
down_revision = "47d85d8042d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mantle", sa.Boolean(), nullable=False, server_default="false"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.drop_column("mantle")

    # ### end Alembic commands ###
