"""empty message

Revision ID: d0f895ce16d0
Revises: d8e9a83e7bbc
Create Date: 2024-09-15 18:37:59.670866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f895ce16d0'
down_revision = 'd8e9a83e7bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maptiler_api_key', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_settings', schema=None) as batch_op:
        batch_op.drop_column('maptiler_api_key')

    # ### end Alembic commands ###
