"""empty message

Revision ID: d1ead0ff6362
Revises: d54a5f859d23
Create Date: 2025-10-09 22:54:01.337755

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d1ead0ff6362"
down_revision = "d54a5f859d23"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ranking_past_weeks", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance_settings", schema=None) as batch_op:
        batch_op.drop_column("ranking_past_weeks")

    # ### end Alembic commands ###
