"""empty message

Revision ID: d54a5f859d23
Revises: b3f3f56d5a7b
Create Date: 2025-09-30 22:03:39.848926

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d54a5f859d23"
down_revision = "b3f3f56d5a7b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "default_starting_position",
                sa.Enum("SIT", "STAND", "CROUCH", "FRENCH", "CANDLE", "LAYDOWN", name="startingpositionenum"),
                server_default="STAND",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance_settings", schema=None) as batch_op:
        batch_op.drop_column("default_starting_position")

    # ### end Alembic commands ###
