"""empty message

Revision ID: ddfa3412d2ff
Revises: 070b390a5efa
Create Date: 2024-12-08 19:00:48.232442

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ddfa3412d2ff"
down_revision = "070b390a5efa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "history_items",
        sa.Column("type", sa.Enum("CREATED", "UPDATED", name="historyitemtypeenum"), nullable=False),
        sa.Column("old_value", sa.String(length=120), nullable=True),
        sa.Column("new_value", sa.String(length=120), nullable=True),
        sa.Column("object_type", sa.Unicode(length=255), nullable=True),
        sa.Column("object_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=True),
        sa.Column("time_updated", sa.DateTime(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("history_items")
    # ### end Alembic commands ###
