"""empty message

Revision ID: e3d4287d48d8
Revises: c605261e6290
Create Date: 2024-04-03 16:05:48.640295

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e3d4287d48d8"
down_revision = "c605261e6290"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ascents",
        sa.Column("line_id", sa.UUID(), nullable=False),
        sa.Column("flash", sa.Boolean(), nullable=False),
        sa.Column("fa", sa.Boolean(), nullable=False),
        sa.Column("soft", sa.Boolean(), nullable=False),
        sa.Column("hard", sa.Boolean(), nullable=False),
        sa.Column("grade_name", sa.String(length=120), nullable=False),
        sa.Column("grade_scale", sa.String(length=120), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=True),
        sa.Column("time_updated", sa.DateTime(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["lines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ascents")
    # ### end Alembic commands ###
