"""empty message

Revision ID: e5da1546a4f7
Revises: 9d8cfafdbd89
Create Date: 2022-09-22 19:56:28.940828

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e5da1546a4f7"
down_revision = "9d8cfafdbd89"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=True),
        sa.Column("time_updated", sa.DateTime(), nullable=True),
        sa.Column("original_filename", sa.String(length=120), nullable=False),
        sa.Column("filename", sa.String(length=120), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("thumbnail_xs", sa.Boolean(), nullable=True),
        sa.Column("thumbnail_s", sa.Boolean(), nullable=True),
        sa.Column("thumbnail_m", sa.Boolean(), nullable=True),
        sa.Column("thumbnail_l", sa.Boolean(), nullable=True),
        sa.Column("thumbnail_xl", sa.Boolean(), nullable=True),
        sa.Column("created_by_id", postgresql.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_table("files")
    # ### end Alembic commands ###
