"""empty message

Revision ID: eb63587cb28b
Revises: ddfa3412d2ff
Create Date: 2024-12-08 19:21:41.607269

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb63587cb28b"
down_revision = "ddfa3412d2ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("history_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("property_name", sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("history_items", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("property_name")

    # ### end Alembic commands ###
