"""empty message

Revision ID: edd3566bce56
Revises: ccc1744ecb5f
Create Date: 2024-06-08 09:23:12.691370

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import orm
from sqlalchemy.orm import declarative_base

from models.enums.line_type_enum import LineTypeEnum

# revision identifiers, used by Alembic.
revision = "edd3566bce56"
down_revision = "ccc1744ecb5f"
branch_labels = None
depends_on = None


Base = declarative_base()

mapping = {
    "CLOSED_PROJECT": -2,
    "OPEN_PROJECT": -1,
    "UNGRADED": 0,
    "1": 1,
    "2": 2,
    "3": 3,
    "4A": 4,
    "4B": 5,
    "4C": 6,
    "5A": 7,
    "5B": 8,
    "5C": 9,
    "6A": 10,
    "6A+": 11,
    "6B": 12,
    "6B+": 13,
    "6C": 14,
    "6C+": 15,
    "7A": 16,
    "7A+": 17,
    "7B": 18,
    "7B+": 19,
    "7C": 20,
    "7C+": 21,
    "8A": 22,
    "8A+": 23,
    "8B": 24,
    "8B+": 25,
    "8C": 26,
    "8C+": 27,
    "9A": 28,
}


class Line(Base):
    __tablename__ = "lines"

    id = sa.Column(sa.Integer, primary_key=True)
    grade_name = sa.Column(sa.String(120), nullable=False)
    grade_scale = sa.Column(sa.String(120), nullable=False)
    grade_value = sa.Column(sa.Integer, nullable=True)
    type = sa.Column(sa.Enum(LineTypeEnum), nullable=False)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.add_column(sa.Column("grade_value", sa.Integer(), nullable=True))

    bind = op.get_bind()
    session = orm.Session(bind=bind)

    for line in session.query(Line):
        line.grade_value = mapping.get(line.grade_name, "")
        session.add(line)

    session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.drop_column("grade_value")

    # ### end Alembic commands ###
