"""Add routesetter and set date to lines.

Revision ID: f1a2b3c4d5e6
Revises: e8f3a2b1c904
Create Date: 2026-06-04

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f1a2b3c4d5e6"
down_revision = "e8f3a2b1c904"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.add_column(sa.Column("routesetter", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("set_date", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.drop_column("set_date")
        batch_op.drop_column("routesetter")

    # ### end Alembic commands ###
