"""Add routesetter and set date to lines, migrating gym setter info from FA fields.

Revision ID: f1a2b3c4d5e6
Revises: e8f3a2b1c904
Create Date: 2026-06-04

For gym-mode instances this migration moves that data into the new columns:

  - fa_name           -> routesetter
  - fa_date           -> set_date
  - only fa_year set  -> set_date = January 1st of that year
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f1a2b3c4d5e6"
down_revision = "e8f3a2b1c904"
branch_labels = None
depends_on = None


def _is_gym_mode(connection) -> bool:
    # use instance setting gym_mode
    return bool(connection.execute(sa.text("SELECT gym_mode FROM instance_settings LIMIT 1")).scalar())


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.add_column(sa.Column("routesetter", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("set_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###

    # Move historical setter info out of the FA fields into the new columns for gym instances.
    connection = op.get_bind()
    if _is_gym_mode(connection):
        connection.execute(
            sa.text(
                """
                UPDATE lines
                SET routesetter = fa_name,
                    set_date = COALESCE(fa_date, make_date(fa_year, 1, 1)),
                    fa_name = NULL,
                    fa_date = NULL,
                    fa_year = NULL
                WHERE fa_name IS NOT NULL OR fa_date IS NOT NULL OR fa_year IS NOT NULL
                """
            )
        )


def downgrade():
    connection = op.get_bind()
    if _is_gym_mode(connection):
        connection.execute(
            sa.text(
                """
                UPDATE lines
                SET fa_name = routesetter,
                    fa_date = set_date,
                    fa_year = NULL
                WHERE routesetter IS NOT NULL OR set_date IS NOT NULL
                """
            )
        )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lines", schema=None) as batch_op:
        batch_op.drop_column("set_date")
        batch_op.drop_column("routesetter")
    # ### end Alembic commands ###
