"""empty message

Revision ID: f6d0d0d98cbf
Revises: 9c7f29f826b9
Create Date: 2025-01-15 11:39:12.300496

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "f6d0d0d98cbf"
down_revision = "9c7f29f826b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
    WITH ranked_ascents AS (
    SELECT
        id,
        created_by_id,
        line_id,
        ROW_NUMBER() OVER (PARTITION BY created_by_id, line_id ORDER BY time_created DESC) AS rnk
    FROM
        ascents
)
DELETE FROM ascents
WHERE id IN (
    SELECT id
    FROM ranked_ascents
    WHERE rnk > 1
);
    """
    )
    with op.batch_alter_table("ascents", schema=None) as batch_op:
        batch_op.create_unique_constraint("_user_line_uc", ["created_by_id", "line_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ascents", schema=None) as batch_op:
        batch_op.drop_constraint("_user_line_uc", type_="unique")

    # ### end Alembic commands ###
