"""empty message

Revision ID: fcfd87218a90
Revises: e883504a579f
Create Date: 2024-03-27 21:51:19.011480

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fcfd87218a90'
down_revision = 'e883504a579f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_settings', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('bar_chart_color', sa.String(length=30), server_default='rgb(213, 30, 38)', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_settings', schema=None) as batch_op:
        batch_op.drop_column('bar_chart_color')

    # ### end Alembic commands ###
