"""empty message

Revision ID: ffb5158bf4ab
Revises: 4355d25e861c
Create Date: 2022-09-23 16:18:35.488496

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ffb5158bf4ab"
down_revision = "4355d25e861c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("deleted", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deleted_at")
    op.drop_column("users", "deleted")
    # ### end Alembic commands ###
