name: Auto-approve PR
on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  auto-approve:
    # Only run this action for the dorthrithil user
    if: github.actor == 'dorthrithil'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto-approve
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.LC_BOT_PAT }}
          review-message: "LocalCragBot here - I approved the PR!\n\nWondering why this is happening? Join the LocalCrag team and be the one approving PRs instead of me!"