name: Auto-approve PR
on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  auto-approve:
    # Only run this action for the dorthrithil user
    if: github.actor == 'dorthrithil'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Auto-approve
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
