name: Auto-approve PR
on:
  pull_request_target:
    types: [ opened, synchronize ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  auto-approve:
    # Only run this action for the dorthrithil user
    if: github.actor == 'dorthrithil'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto-approve
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.LC_BOT_PAT }}
          review-message: "Auto approved PR: Join the LocalCrag team, so we can review your PRs instead of letting bots auto approve them."